version: "3.9"

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: reptor-interretialis-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # as far as i know docker compose does not allows this did you check ?
    restart: unless-stopped
