    upstream backend_stream { # this whole section needs to be generated. not staticly placed 
        server www.thunderdomain.com;
        server app.thunderdomain.com;
        server api.thunderdomain.com;
        server beta.thunderdomain.com;
        server test.thunderdomain.com;
        server dev.thunderdomain.com;
        server staging.thunderdomain.com;
    }

    server {
       listen 80;
       server_name thunderdomain.com; # this needs to be added by the script

       location / {
       proxy_pass http://backend_stream;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
